### ISSUE TITLE
(Deployment error) Teamspeak

### ISSUE THREAD

**Issue by jenslys** [PAPAMICA/docker-compose-collection#23]
Getting this error when trying to deploy the Teamspeak server stack:

```
Deployment error
failed to deploy a stack: time="2023-07-10T19:35:37Z" level=warning msg="The \"SERVICE2\" variable is not set. Defaulting to a blank string." network default declared as external, but could not be found
```

ENV:

![image](https://github.com/PAPAMICA/docker-compose-collection/assets/69081683/ddcd02f1-ccbc-4839-b27b-b99c5020f1de)

**Comment by mastervash** [comment]
Those empty fields aren't just for show. Try filling them in with the information you set when you ran the traefik installation script that these compose files are meant to accompany.  

Hint: Your Traefik network name is probably "proxy" and your service url is going to be the (sub)domain you expect to be using for Teamspeak. 😊

If you still get an error about "proxy" network not found, you should probably check [PAPAMICA/docker-environment](https://github.com/PAPAMICA/docker-environment/tree/main)
